### ISSUE TITLE
EC - Doctor: Forgot Password

### ISSUE THREAD

**Issue by lburkett** [lburkett/HealthCareSystem#11]
Accessed when the doctor clicks the "Forgot Password" button at the Doctor Landing Page.  The doctor enters their email address tied to their account and the system will send an email to that email address that will direct the doctor to reset their password.

**Comment by nbhambha** [comment]
UI part is done, will be working on the implementation.

**Comment by spencerbyw** [comment]
All done. Fires emails out like a chain gun.
