### ISSUE TITLE
Doctor: Change Password Page

### ISSUE THREAD

**Issue by lburkett** [lburkett/HealthCareSystem#12]
Accessed when the doctor clicks the "Change Password" button on the Doctor Landing Page.  Allows the doctor to update their password.

**Comment by nbhambha** [comment]
Spancer did the UI, I'll get started on the implementation

**Comment by spencerbyw** [comment]
Spencer*

:wink:

**Comment by nbhambha** [comment]
Oh yeah, sorry about that Spencer.

**Comment by spencerbyw** [comment]
Update to match recent hashing changes. (I'll work on it later today.)

**Comment by spencerbyw** [comment]
All done.
