### ISSUE TITLE
install.php doesn't like $_SESSION variables (lines 81 & 82)

### ISSUE THREAD

**Issue by spencerbyw** [lburkett/HealthCareSystem#16]
I'm not entirely sure why but if you are logged in, or have logged in at all recently (i.e. a session array has been created) when you navigate to install.php it won't let you install. It just keeps showing the green bar. Not even deleting the database helps.

The only way I got around it was by opening an incognito tab (no stored session data) in Chrome and installing that way.

**Comment by lburkett** [comment]
Should be fixed now, if you want to give it a check.  I'll let you close this issue if all is well or you can just comment again if something still isn't right!

**Comment by spencerbyw** [comment]
Works beautifully.
