### ISSUE TITLE
Logout doesn't logout

### ISSUE THREAD

**Issue by spencerbyw** [lburkett/HealthCareSystem#17]
In doctorHome.php, if you click logout and then navigate back to doctorHome.php manually... you're not actually logged out. Same goes for the other doctor-only pages.

**Comment by lburkett** [comment]
Should be fixed, I'll let you close. For other pages that need to do the check for authenticated users:
* add ```require_once 'phpscripts/authenticate.php';``` 
* and after ```session_start();``` add the following:
```php
if(!isLoggedIn()) {
    redirectAndExit('login.php');
}
```

**Comment by spencerbyw** [comment]
Appears to be working just fine. Nice job!
