### ISSUE TITLE
Redirect on pages that only a doctor should see

### ISSUE THREAD

**Issue by spencerbyw** [lburkett/HealthCareSystem#18]
For example, if someone manually visits doctorHome.php without having logged in, things break so this should be prevented.

If we know what to check for, we can use the redirectAndExit($script) function from common.php to go back to index.php if someone navigates to a doctor-only page. Just need to check at the top of the page before we start running anything.

**Comment by lburkett** [comment]
Fixed with the following:
```php
if(!isLoggedIn()) {
    redirectAndExit('login.php');
}
```
