### ISSUE TITLE
Doctor: Login Page

### ISSUE THREAD

**Issue by lburkett** [lburkett/HealthCareSystem#6]
Accessed via clicking the "Doctor" button on index.php.

**Comment by spencerbyw** [comment]
We need to be hashing the passwords that we store in the database.

**Comment by lburkett** [comment]
So I have the hash_passwords working and to get it working for everyone would be an easy change, the problem is we would have to make a way to manually add doctors to the database.  The passwords are stored in hash form in the database, so by us going in and editing the password attributes in init.sql it produces unhashed passwords.

**Comment by spencerbyw** [comment]
All done here, correct?

**Comment by lburkett** [comment]
Yessir, it should all properly hash correctly and only check against properly stored hashed passwords.
